### PR TITLE
Fixes issues with Postgres

### PR DESCRIPTION
**Pull request by Syxton**
Changes varchar fields to bigint.
retains data and deprecates old field.
Fixes an sql group by statement

### CODE REVIEW

**Comment by Syxton** [comment]
Here is an upgrade to fix #26

**Comment by Syxton** [comment]
To explain what the upgrade process does,  The reason the itemid and categoryid field were changed in the first place was to allow for non category flags like "favs" and "lastviewed".  Now instead favs are denoted by a -1 and lastviewed is -2.  This insures that the id's are integers, which allows the data to be compared crossdb compatible.  The original fields are renamed. itemid becomes itemid_depr and categoryid becomes categoryid_depr.  A new itemid and categoryid field is created, and the data is then transferred over, converting all "favs" to -1 and all "lastviewed" to -2.  The original fields and their data are retained just in case of an issue in the upgrade.  This has been tested on a postgres server and a mysql server running Moodle 3.0 but it should work for all Moodle 2.x as well.

**Comment by upats** [comment]
Thanks @Syxton ! My student developers are gone for the summer so I don't have the resources to make updates at the moment. I appreciate you taking a look at this. I'll run the update real quick on my dev system and if it looks good I'll make the merge.

**Comment by Syxton** [comment]
Once this is tested and merged, I have another pull request that adds Travis CI support and passes all tests.  That should help get it into the plugin database.

**Pull request merged**
